set(CMAKE_THREAD_PREFER_PTHREAD ON) # tells cmake to prefer posix threads over other options
set(THREADS_PREFER_PTHREAD_FLAG ON) # tells cmake to prefer posix threads compiler and linker flags over other options
find_package(Threads REQUIRED)
set(AIECAD_HAVE_PTHREAD "${CMAKE_USE_PTHREADS_INIT}")
list(APPEND AIECAD_LINK_LIBS Threads::Threads)

find_package(XRT QUIET)
if (XRT_FOUND)
    list(APPEND AIECAD_INCLUDE_DIRS "${XRT_INCLUDE_DIR}")
    list(APPEND AIECAD_LINK_LIBS XRT::coreutil)
endif ()

find_package(glfw3 CONFIG REQUIRED)
find_package(OpenGL REQUIRED)
find_package(imgui CONFIG REQUIRED)
find_package(glm CONFIG REQUIRED)
find_package(spdlog CONFIG REQUIRED)
find_package(glad CONFIG REQUIRED)
#get_target_property(_imgui_includes imgui::imgui INTERFACE_INCLUDE_DIRECTORIES)

list(APPEND AIECAD_LINK_LIBS glfw glad::glad imgui::imgui glm::glm spdlog::spdlog_header_only OpenGL::GL )

# Extract include directories from targets, handling generator expressions
# For multi-config generators, we need to get the actual paths
get_target_property(_glfw_inc glfw INTERFACE_INCLUDE_DIRECTORIES)
if(_glfw_inc AND NOT _glfw_inc STREQUAL "_glfw_inc-NOTFOUND")
    # Extract path from generator expression like $<$<CONFIG:Release>:C:/path/to/include>
    string(REGEX REPLACE "\\$<\\$<CONFIG:[^>]+>:" "" _glfw_path "${_glfw_inc}")
    string(REGEX REPLACE ">" "" _glfw_path "${_glfw_path}")
    if(_glfw_path AND EXISTS "${_glfw_path}")
        list(APPEND AIECAD_INCLUDE_DIRS "${_glfw_path}")
        message(STATUS "Added GLFW include: ${_glfw_path}")
    endif()
endif()

get_target_property(_spdlog_inc spdlog::spdlog_header_only INTERFACE_INCLUDE_DIRECTORIES)
if(_spdlog_inc AND NOT _spdlog_inc STREQUAL "_spdlog_inc-NOTFOUND")
    string(REGEX REPLACE "\\$<\\$<CONFIG:[^>]+>:" "" _spdlog_path "${_spdlog_inc}")
    string(REGEX REPLACE ">" "" _spdlog_path "${_spdlog_path}")
    if(_spdlog_path AND EXISTS "${_spdlog_path}")
        list(APPEND AIECAD_INCLUDE_DIRS "${_spdlog_path}")
        message(STATUS "Added spdlog include: ${_spdlog_path}")
    endif()
endif()

# Also add fmt include directory (spdlog depends on it)
if(TARGET fmt::fmt)
    get_target_property(_fmt_inc fmt::fmt INTERFACE_INCLUDE_DIRECTORIES)
    if(_fmt_inc AND NOT _fmt_inc STREQUAL "_fmt_inc-NOTFOUND")
        string(REGEX REPLACE "\\$<\\$<CONFIG:[^>]+>:" "" _fmt_path "${_fmt_inc}")
        string(REGEX REPLACE ">" "" _fmt_path "${_fmt_path}")
        if(_fmt_path AND EXISTS "${_fmt_path}")
            list(APPEND AIECAD_INCLUDE_DIRS "${_fmt_path}")
            message(STATUS "Added fmt include: ${_fmt_path}")
        endif()
    endif()
endif()

# Add glad include directory
if(TARGET glad::glad)
    get_target_property(_glad_inc glad::glad INTERFACE_INCLUDE_DIRECTORIES)
    if(_glad_inc AND NOT _glad_inc STREQUAL "_glad_inc-NOTFOUND")
        string(REGEX REPLACE "\\$<\\$<CONFIG:[^>]+>:" "" _glad_path "${_glad_inc}")
        string(REGEX REPLACE ">" "" _glad_path "${_glad_path}")
        if(_glad_path AND EXISTS "${_glad_path}")
            list(APPEND AIECAD_INCLUDE_DIRS "${_glad_path}")
            message(STATUS "Added glad include: ${_glad_path}")
        endif()
    endif()
endif()

# Add gtest include directory
if(TARGET gtest::gtest)
    get_target_property(_gtest_inc gtest::gtest INTERFACE_INCLUDE_DIRECTORIES)
    if(_gtest_inc AND NOT _gtest_inc STREQUAL "_gtest_inc-NOTFOUND")
        string(REGEX REPLACE "\\$<\\$<CONFIG:[^>]+>:" "" _gtest_path "${_gtest_inc}")
        string(REGEX REPLACE ">" "" _gtest_path "${_gtest_path}")
        if(_gtest_path AND EXISTS "${_gtest_path}")
            list(APPEND AIECAD_INCLUDE_DIRS "${_gtest_path}")
            message(STATUS "Added gtest include: ${_gtest_path}")
        endif()
    endif()
endif()

get_target_property(_imgui_inc  imgui::imgui INTERFACE_INCLUDE_DIRECTORIES)
get_target_property(_imgui_defs imgui::imgui INTERFACE_COMPILE_DEFINITIONS)
list(APPEND AIECAD_COMPILE_DEFS "${IMGUI_ENABLE_DOCKING}" AIECAD_DEBUG)